### ISSUE TITLE
CanonicalizerTests: fix FHIRPath namespace

### ISSUE THREAD

**Issue by qligier** [ahdis/matchbox-int-tests#5]
```
java.lang.NoClassDefFoundError: org/hl7/fhir/r4/utils/FHIRPathEngine$IEvaluationContext

	at org.hl7.fhir.r4.hapi.ctx.FhirR4.createFhirPathExecutor(FhirR4.java:45)
	at ca.uhn.fhir.context.FhirContext.newFhirPath(FhirContext.java:859)
	at health.matchbox.server.CanonicalizerTests.patient(CanonicalizerTests.java:69)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
```

**Comment by qligier** [comment]
Fixed with https://github.com/ahdis/matchbox/pull/213/commits/c5b5c79443def276ca025c0070d506db77c38f64
