### ISSUE TITLE
Validating resource /igs/ch.fhir.ig.ch-emed#4.0.1.tgz-MedicationRequest-MedReq-ChangeMedication fails

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox-int-tests#6]
```xml
  <testcase name="testValidate(String, Resource)[34]" classname="health.matchbox.engine.IgValidationTests" time="2.971">
    <failure message="expected: &lt;true&gt; but was: &lt;false&gt;" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:183)
	at health.matchbox.engine.IgValidationTests.testValidate(IgValidationTests.java:84)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
]]></failure>
    <system-out><![CDATA[2024-04-05 15:03:35.846 [main] INFO  h.matchbox.engine.IgValidationTests [IgValidationTests.java:60] Validating resource /igs/ch.fhir.ig.ch-emed#4.0.1.tgz-MedicationRequest-MedReq-ChangeMedication
2024-04-05 15:03:35.848 [main] INFO  c.a.matchbox.engine.MatchboxEngine [MatchboxEngine.java:527] Using profile for validation http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-medicationrequest-changed|4.0.1 (2023-12-28T10:07:10+01:00)
Validate MedicationRequest against http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-medicationrequest-changed|4.0.1Validate Dosage against http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-dosage-medicationrequest|4.0.1..........20..........40..........60..........80.........|
Validate Dosage against http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-dosage-split|4.0.1..........20..........40..........60..........80.........|
..........20.2024-04-05 15:03:36.425 [hapi-fhir-jpa-scheduler-clustered-1] INFO  c.u.f.j.s.c.DatabaseSearchCacheSvcImpl [DatabaseSearchCacheSvcImpl.java:256] Deleted 0 expired searches
.........40..........60.........|
2024-04-05 15:03:38.810 [main] INFO  h.matchbox.engine.IgValidationTests [IgValidationTests.java:75] ERROR 1
2024-04-05 15:03:38.811 [main] INFO  h.matchbox.engine.IgValidationTests [IgValidationTests.java:75] INFORMATION 2
2024-04-05 15:03:38.811 [main] ERROR h.matchbox.engine.IgValidationTests [IgValidationTests.java:79] [INFORMATION][INFORMATIONAL] This element does not match any known slice defined in the profile http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-medicationrequest-changed|4.0.1 (this may not be a problem, but you should check that it's not intended to match a slice)
2024-04-05 15:03:38.811 [main] ERROR h.matchbox.engine.IgValidationTests [IgValidationTests.java:79] [ERROR][STRUCTURE] Slice 'MedicationRequest.supportingInformation:partOf': a matching slice is required, but not found (from http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-medicationrequest-changed|4.0.1). Note that other slices are allowed in addition to this required slice
2024-04-05 15:03:38.811 [main] ERROR h.matchbox.engine.IgValidationTests [IgValidationTests.java:79] [INFORMATION][NOTFOUND] A definition for CodeSystem 'urn:oid:2.51.1.1' could not be found, so the code cannot be validated
]]></system-out>
  </testcase>
```

**Comment by oliveregger** [comment]
This error is actually correct. The validator cannot check that the supportingInformation.reference conforms to the profile.

**Comment by qligier** [comment]
That's the reason I disabled validation of Bundles and Compositions, resources are not always resolvable in these examples.

But, from my understanding, it seems that you are validating `MedicationRequest-MedReq-ChangeMedication`, which should also be ignored:

https://github.com/ahdis/matchbox-int-tests/blob/a55b40922089fd5e533d46691e6d51e1dbae3d8c/src/test/java/health/matchbox/engine/IgValidationTests.java#L117-L126

**Comment by oliveregger** [comment]
a) Bundles should contain all information, however there seem to be xhtml errors in the narrative if we use them standalone
b) i think MedicationRequest-MedReq-ChangeMedication is not catched with this rule, probably because fn starts with the ig name? Validating resource /igs/ch.fhir.ig.ch-emed#4.0.1.tgz-MedicationRequest-MedReq-ChangeMedication

**Comment by oliveregger** [comment]
we should just validate Bundle's for CH EMED, everything else is not worth it
